# Generated by Django 2.2.2 on 2019-09-15 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Department Name')),
            ],
            options={
                'db_table': 'departments',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Employee Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email Address')),
                ('dob', models.DateTimeField(help_text='Format: yyyy/mm/dd', verbose_name='Date of Birth')),
                ('salary', models.FloatField(verbose_name='Monthly Salary')),
                ('photo', models.FileField(blank=True, default='blank.png', upload_to='myimage')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='less4App.Department')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
