# Generated by Django 2.2.2 on 2019-09-15 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('less4App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, default='Admin', on_delete=django.db.models.deletion.CASCADE, to='less4App.Department'),
        ),
    ]
