# Generated by Django 2.2.2 on 2019-09-15 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('less4App', '0002_auto_20190915_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='less4App.Department'),
        ),
    ]
